name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    

jobs:
  build:
    runs-on: node-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install SCSS compiler
      run: npm -g install node-sass
    - name: Build CSS
      run: make
    - name: Install theme
      run: make install
